# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Randall.Bower/Documents/Courses/CS220/Code/TicTacToeButtonsGui.ui'
#
# Created: Tue Jan  6 14:36:18 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TicTacToe(object):
    def setupUi(self, TicTacToe):
        TicTacToe.setObjectName(_fromUtf8("TicTacToe"))
        TicTacToe.resize(480, 500)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        TicTacToe.setPalette(palette)
        self.gui_layout = QtGui.QVBoxLayout(TicTacToe)
        self.gui_layout.setObjectName(_fromUtf8("gui_layout"))
        self.main_layout = QtGui.QVBoxLayout()
        self.main_layout.setObjectName(_fromUtf8("main_layout"))
        self.status_label = QtGui.QLabel(TicTacToe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setMinimumSize(QtCore.QSize(0, 20))
        self.status_label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.status_label.setFont(font)
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.main_layout.addWidget(self.status_label)
        self.grid_layout = QtGui.QGridLayout()
        self.grid_layout.setObjectName(_fromUtf8("grid_layout"))
        self.button_1 = QtGui.QPushButton(TicTacToe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_1.sizePolicy().hasHeightForWidth())
        self.button_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.button_1.setFont(font)
        self.button_1.setObjectName(_fromUtf8("button_1"))
        self.grid_layout.addWidget(self.button_1, 0, 0, 1, 1)
        self.button_2 = QtGui.QPushButton(TicTacToe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_2.sizePolicy().hasHeightForWidth())
        self.button_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.button_2.setFont(font)
        self.button_2.setObjectName(_fromUtf8("button_2"))
        self.grid_layout.addWidget(self.button_2, 0, 1, 1, 1)
        self.button_3 = QtGui.QPushButton(TicTacToe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_3.sizePolicy().hasHeightForWidth())
        self.button_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.button_3.setFont(font)
        self.button_3.setObjectName(_fromUtf8("button_3"))
        self.grid_layout.addWidget(self.button_3, 0, 2, 1, 1)
        self.button_4 = QtGui.QPushButton(TicTacToe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_4.sizePolicy().hasHeightForWidth())
        self.button_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.button_4.setFont(font)
        self.button_4.setObjectName(_fromUtf8("button_4"))
        self.grid_layout.addWidget(self.button_4, 1, 0, 1, 1)
        self.button_5 = QtGui.QPushButton(TicTacToe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_5.sizePolicy().hasHeightForWidth())
        self.button_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.button_5.setFont(font)
        self.button_5.setObjectName(_fromUtf8("button_5"))
        self.grid_layout.addWidget(self.button_5, 1, 1, 1, 1)
        self.button_6 = QtGui.QPushButton(TicTacToe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_6.sizePolicy().hasHeightForWidth())
        self.button_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.button_6.setFont(font)
        self.button_6.setObjectName(_fromUtf8("button_6"))
        self.grid_layout.addWidget(self.button_6, 1, 2, 1, 1)
        self.button_7 = QtGui.QPushButton(TicTacToe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_7.sizePolicy().hasHeightForWidth())
        self.button_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.button_7.setFont(font)
        self.button_7.setObjectName(_fromUtf8("button_7"))
        self.grid_layout.addWidget(self.button_7, 2, 0, 1, 1)
        self.button_8 = QtGui.QPushButton(TicTacToe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_8.sizePolicy().hasHeightForWidth())
        self.button_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.button_8.setFont(font)
        self.button_8.setObjectName(_fromUtf8("button_8"))
        self.grid_layout.addWidget(self.button_8, 2, 1, 1, 1)
        self.button_9 = QtGui.QPushButton(TicTacToe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_9.sizePolicy().hasHeightForWidth())
        self.button_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.button_9.setFont(font)
        self.button_9.setObjectName(_fromUtf8("button_9"))
        self.grid_layout.addWidget(self.button_9, 2, 2, 1, 1)
        self.main_layout.addLayout(self.grid_layout)
        self.gui_layout.addLayout(self.main_layout)

        self.retranslateUi(TicTacToe)
        QtCore.QMetaObject.connectSlotsByName(TicTacToe)

    def retranslateUi(self, TicTacToe):
        TicTacToe.setWindowTitle(_translate("TicTacToe", "Tic Tac Toe", None))
        self.status_label.setText(_translate("TicTacToe", "Player X\'s turn...", None))
        self.button_1.setText(_translate("TicTacToe", " ", None))
        self.button_2.setText(_translate("TicTacToe", " ", None))
        self.button_3.setText(_translate("TicTacToe", " ", None))
        self.button_4.setText(_translate("TicTacToe", " ", None))
        self.button_5.setText(_translate("TicTacToe", " ", None))
        self.button_6.setText(_translate("TicTacToe", " ", None))
        self.button_7.setText(_translate("TicTacToe", " ", None))
        self.button_8.setText(_translate("TicTacToe", " ", None))
        self.button_9.setText(_translate("TicTacToe", " ", None))

