# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/C18Jacob.Orner/Documents/Schoolwork/USAFA_CS210_2015/PEXes/PEX3/PEX3_StarGui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StarGui(object):
    def setupUi(self, StarGui):
        StarGui.setObjectName(_fromUtf8("StarGui"))
        StarGui.resize(673, 573)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        StarGui.setPalette(palette)
        self.centralwidget = QtGui.QWidget(StarGui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.window_layout = QtGui.QHBoxLayout(self.centralwidget)
        self.window_layout.setObjectName(_fromUtf8("window_layout"))
        self.main_layout = QtGui.QHBoxLayout()
        self.main_layout.setObjectName(_fromUtf8("main_layout"))
        self.drawing_widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.drawing_widget.sizePolicy().hasHeightForWidth())
        self.drawing_widget.setSizePolicy(sizePolicy)
        self.drawing_widget.setMinimumSize(QtCore.QSize(512, 512))
        self.drawing_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.drawing_widget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(12)
        self.drawing_widget.setFont(font)
        self.drawing_widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.drawing_widget.setAutoFillBackground(True)
        self.drawing_widget.setObjectName(_fromUtf8("drawing_widget"))
        self.main_layout.addWidget(self.drawing_widget)
        self.vertical_line = QtGui.QFrame(self.centralwidget)
        self.vertical_line.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line.setObjectName(_fromUtf8("vertical_line"))
        self.main_layout.addWidget(self.vertical_line)
        self.controls_layout = QtGui.QVBoxLayout()
        self.controls_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.controls_layout.setMargin(8)
        self.controls_layout.setObjectName(_fromUtf8("controls_layout"))
        spacerItem = QtGui.QSpacerItem(128, 16777215, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.controls_layout.addItem(spacerItem)
        self.line_top = QtGui.QFrame(self.centralwidget)
        self.line_top.setFrameShape(QtGui.QFrame.HLine)
        self.line_top.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_top.setObjectName(_fromUtf8("line_top"))
        self.controls_layout.addWidget(self.line_top)
        self.constellation_layout = QtGui.QVBoxLayout()
        self.constellation_layout.setObjectName(_fromUtf8("constellation_layout"))
        self.constellation_label = QtGui.QLabel(self.centralwidget)
        self.constellation_label.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.constellation_label.setFont(font)
        self.constellation_label.setObjectName(_fromUtf8("constellation_label"))
        self.constellation_layout.addWidget(self.constellation_label)
        self.none_button = QtGui.QRadioButton(self.centralwidget)
        self.none_button.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.none_button.setFont(font)
        self.none_button.setChecked(True)
        self.none_button.setObjectName(_fromUtf8("none_button"))
        self.constellation_group = QtGui.QButtonGroup(StarGui)
        self.constellation_group.setObjectName(_fromUtf8("constellation_group"))
        self.constellation_group.addButton(self.none_button)
        self.constellation_layout.addWidget(self.none_button)
        self.big_dipper_button = QtGui.QRadioButton(self.centralwidget)
        self.big_dipper_button.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.big_dipper_button.setFont(font)
        self.big_dipper_button.setObjectName(_fromUtf8("big_dipper_button"))
        self.constellation_group.addButton(self.big_dipper_button)
        self.constellation_layout.addWidget(self.big_dipper_button)
        self.bootes_button = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bootes_button.setFont(font)
        self.bootes_button.setChecked(False)
        self.bootes_button.setObjectName(_fromUtf8("bootes_button"))
        self.constellation_group.addButton(self.bootes_button)
        self.constellation_layout.addWidget(self.bootes_button)
        self.cassiopeia_button = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cassiopeia_button.setFont(font)
        self.cassiopeia_button.setObjectName(_fromUtf8("cassiopeia_button"))
        self.constellation_group.addButton(self.cassiopeia_button)
        self.constellation_layout.addWidget(self.cassiopeia_button)
        self.cygnet_button = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cygnet_button.setFont(font)
        self.cygnet_button.setObjectName(_fromUtf8("cygnet_button"))
        self.constellation_group.addButton(self.cygnet_button)
        self.constellation_layout.addWidget(self.cygnet_button)
        self.gemini_button = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gemini_button.setFont(font)
        self.gemini_button.setObjectName(_fromUtf8("gemini_button"))
        self.constellation_group.addButton(self.gemini_button)
        self.constellation_layout.addWidget(self.gemini_button)
        self.hydra_button = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hydra_button.setFont(font)
        self.hydra_button.setObjectName(_fromUtf8("hydra_button"))
        self.constellation_group.addButton(self.hydra_button)
        self.constellation_layout.addWidget(self.hydra_button)
        self.ursa_major_button = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ursa_major_button.setFont(font)
        self.ursa_major_button.setObjectName(_fromUtf8("ursa_major_button"))
        self.constellation_group.addButton(self.ursa_major_button)
        self.constellation_layout.addWidget(self.ursa_major_button)
        self.ursa_minor_button = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ursa_minor_button.setFont(font)
        self.ursa_minor_button.setObjectName(_fromUtf8("ursa_minor_button"))
        self.constellation_group.addButton(self.ursa_minor_button)
        self.constellation_layout.addWidget(self.ursa_minor_button)
        self.controls_layout.addLayout(self.constellation_layout)
        self.line_bottom = QtGui.QFrame(self.centralwidget)
        self.line_bottom.setFrameShape(QtGui.QFrame.HLine)
        self.line_bottom.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_bottom.setObjectName(_fromUtf8("line_bottom"))
        self.controls_layout.addWidget(self.line_bottom)
        spacerItem1 = QtGui.QSpacerItem(128, 16777215, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.controls_layout.addItem(spacerItem1)
        self.main_layout.addLayout(self.controls_layout)
        self.window_layout.addLayout(self.main_layout)
        StarGui.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(StarGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_map = QtGui.QMenu(self.menubar)
        self.menu_map.setObjectName(_fromUtf8("menu_map"))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        self.menu_star = QtGui.QMenu(self.menubar)
        self.menu_star.setObjectName(_fromUtf8("menu_star"))
        StarGui.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(StarGui)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        StarGui.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(StarGui)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(StarGui)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(StarGui)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.action_save = QtGui.QAction(StarGui)
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_open_file = QtGui.QAction(StarGui)
        self.action_open_file.setObjectName(_fromUtf8("action_open_file"))
        self.action_insert_vertex = QtGui.QAction(StarGui)
        self.action_insert_vertex.setObjectName(_fromUtf8("action_insert_vertex"))
        self.action_insert_edge = QtGui.QAction(StarGui)
        self.action_insert_edge.setObjectName(_fromUtf8("action_insert_edge"))
        self.action_about = QtGui.QAction(StarGui)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action_new = QtGui.QAction(StarGui)
        self.action_new.setObjectName(_fromUtf8("action_new"))
        self.action_node = QtGui.QAction(StarGui)
        self.action_node.setObjectName(_fromUtf8("action_node"))
        self.action_edge = QtGui.QAction(StarGui)
        self.action_edge.setObjectName(_fromUtf8("action_edge"))
        self.action_open = QtGui.QAction(StarGui)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_save_image = QtGui.QAction(StarGui)
        self.action_save_image.setObjectName(_fromUtf8("action_save_image"))
        self.action_find_by_name = QtGui.QAction(StarGui)
        self.action_find_by_name.setObjectName(_fromUtf8("action_find_by_name"))
        self.action_name = QtGui.QAction(StarGui)
        self.action_name.setObjectName(_fromUtf8("action_name"))
        self.action_draper_number = QtGui.QAction(StarGui)
        self.action_draper_number.setObjectName(_fromUtf8("action_draper_number"))
        self.action_harvard_revised_number = QtGui.QAction(StarGui)
        self.action_harvard_revised_number.setObjectName(_fromUtf8("action_harvard_revised_number"))
        self.action_exit = QtGui.QAction(StarGui)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.menu_map.addAction(self.action_open_file)
        self.menu_map.addAction(self.action_exit)
        self.menu_help.addAction(self.action_about)
        self.menu_star.addAction(self.action_name)
        self.menu_star.addAction(self.action_draper_number)
        self.menu_star.addAction(self.action_harvard_revised_number)
        self.menubar.addAction(self.menu_map.menuAction())
        self.menubar.addAction(self.menu_star.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(StarGui)
        QtCore.QMetaObject.connectSlotsByName(StarGui)

    def retranslateUi(self, StarGui):
        StarGui.setWindowTitle(_translate("StarGui", "Star Map", None))
        self.constellation_label.setText(_translate("StarGui", "Constellation", None))
        self.none_button.setText(_translate("StarGui", "None", None))
        self.big_dipper_button.setText(_translate("StarGui", "Big Dipper", None))
        self.bootes_button.setText(_translate("StarGui", "Bootes", None))
        self.cassiopeia_button.setText(_translate("StarGui", "Cassiopeia", None))
        self.cygnet_button.setText(_translate("StarGui", "Cygnet", None))
        self.gemini_button.setText(_translate("StarGui", "Gemini", None))
        self.hydra_button.setText(_translate("StarGui", "Hydra", None))
        self.ursa_major_button.setText(_translate("StarGui", "Ursa Major", None))
        self.ursa_minor_button.setText(_translate("StarGui", "Ursa Minor", None))
        self.menu_map.setTitle(_translate("StarGui", "Map", None))
        self.menu_help.setTitle(_translate("StarGui", "Help", None))
        self.menu_star.setTitle(_translate("StarGui", "Star", None))
        self.actionOpen.setText(_translate("StarGui", "Open...", None))
        self.actionSave.setText(_translate("StarGui", "Save", None))
        self.actionSave_As.setText(_translate("StarGui", "Save As...", None))
        self.action_save.setText(_translate("StarGui", "Save...", None))
        self.action_open_file.setText(_translate("StarGui", "Open...", None))
        self.action_insert_vertex.setText(_translate("StarGui", "Vertex...", None))
        self.action_insert_edge.setText(_translate("StarGui", "Edge...", None))
        self.action_about.setText(_translate("StarGui", "About", None))
        self.action_new.setText(_translate("StarGui", "New", None))
        self.action_node.setText(_translate("StarGui", "Node...", None))
        self.action_edge.setText(_translate("StarGui", "Edge...", None))
        self.action_open.setText(_translate("StarGui", "Open...", None))
        self.action_save_image.setText(_translate("StarGui", "Save Image...", None))
        self.action_find_by_name.setText(_translate("StarGui", "Find by Name...", None))
        self.action_name.setText(_translate("StarGui", "Search by Name", None))
        self.action_draper_number.setText(_translate("StarGui", "Search by Draper Number", None))
        self.action_harvard_revised_number.setText(_translate("StarGui", "Search by Harvard Revised Number", None))
        self.action_exit.setText(_translate("StarGui", "Exit", None))

