# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Randall.Bower/Documents/Courses/CS210/USAFA_CS210_2015_Working/Labs/Gooey/SpotGui.ui'
#
# Created: Tue Oct 27 11:49:33 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SpotGui(object):
    def setupUi(self, SpotGui):
        SpotGui.setObjectName(_fromUtf8("SpotGui"))
        SpotGui.resize(673, 573)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        SpotGui.setPalette(palette)
        self.centralwidget = QtGui.QWidget(SpotGui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.window_layout = QtGui.QHBoxLayout(self.centralwidget)
        self.window_layout.setObjectName(_fromUtf8("window_layout"))
        self.main_layout = QtGui.QHBoxLayout()
        self.main_layout.setObjectName(_fromUtf8("main_layout"))
        self.drawing_widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.drawing_widget.sizePolicy().hasHeightForWidth())
        self.drawing_widget.setSizePolicy(sizePolicy)
        self.drawing_widget.setMinimumSize(QtCore.QSize(512, 512))
        self.drawing_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.drawing_widget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(12)
        self.drawing_widget.setFont(font)
        self.drawing_widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.drawing_widget.setAutoFillBackground(True)
        self.drawing_widget.setObjectName(_fromUtf8("drawing_widget"))
        self.main_layout.addWidget(self.drawing_widget)
        self.vertical_line = QtGui.QFrame(self.centralwidget)
        self.vertical_line.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line.setObjectName(_fromUtf8("vertical_line"))
        self.main_layout.addWidget(self.vertical_line)
        self.controls_layout = QtGui.QVBoxLayout()
        self.controls_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.controls_layout.setMargin(8)
        self.controls_layout.setObjectName(_fromUtf8("controls_layout"))
        spacerItem = QtGui.QSpacerItem(128, 16777215, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.controls_layout.addItem(spacerItem)
        self.line_top = QtGui.QFrame(self.centralwidget)
        self.line_top.setFrameShape(QtGui.QFrame.HLine)
        self.line_top.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_top.setObjectName(_fromUtf8("line_top"))
        self.controls_layout.addWidget(self.line_top)
        self.color_layout = QtGui.QVBoxLayout()
        self.color_layout.setObjectName(_fromUtf8("color_layout"))
        self.color_label = QtGui.QLabel(self.centralwidget)
        self.color_label.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.color_label.setFont(font)
        self.color_label.setObjectName(_fromUtf8("color_label"))
        self.color_layout.addWidget(self.color_label)
        self.red_button = QtGui.QRadioButton(self.centralwidget)
        self.red_button.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.red_button.setFont(font)
        self.red_button.setChecked(False)
        self.red_button.setObjectName(_fromUtf8("red_button"))
        self.color_group = QtGui.QButtonGroup(SpotGui)
        self.color_group.setObjectName(_fromUtf8("color_group"))
        self.color_group.addButton(self.red_button)
        self.color_layout.addWidget(self.red_button)
        self.green_button = QtGui.QRadioButton(self.centralwidget)
        self.green_button.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.green_button.setFont(font)
        self.green_button.setObjectName(_fromUtf8("green_button"))
        self.color_group.addButton(self.green_button)
        self.color_layout.addWidget(self.green_button)
        self.blue_button = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.blue_button.setFont(font)
        self.blue_button.setChecked(True)
        self.blue_button.setObjectName(_fromUtf8("blue_button"))
        self.color_group.addButton(self.blue_button)
        self.color_layout.addWidget(self.blue_button)
        self.yellow_button = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yellow_button.setFont(font)
        self.yellow_button.setObjectName(_fromUtf8("yellow_button"))
        self.color_group.addButton(self.yellow_button)
        self.color_layout.addWidget(self.yellow_button)
        self.cyan_button = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cyan_button.setFont(font)
        self.cyan_button.setObjectName(_fromUtf8("cyan_button"))
        self.color_group.addButton(self.cyan_button)
        self.color_layout.addWidget(self.cyan_button)
        self.magenta_button = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.magenta_button.setFont(font)
        self.magenta_button.setObjectName(_fromUtf8("magenta_button"))
        self.color_group.addButton(self.magenta_button)
        self.color_layout.addWidget(self.magenta_button)
        self.controls_layout.addLayout(self.color_layout)
        self.line_bottom = QtGui.QFrame(self.centralwidget)
        self.line_bottom.setFrameShape(QtGui.QFrame.HLine)
        self.line_bottom.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_bottom.setObjectName(_fromUtf8("line_bottom"))
        self.controls_layout.addWidget(self.line_bottom)
        spacerItem1 = QtGui.QSpacerItem(128, 16777215, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.controls_layout.addItem(spacerItem1)
        self.main_layout.addLayout(self.controls_layout)
        self.window_layout.addLayout(self.main_layout)
        SpotGui.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SpotGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_app = QtGui.QMenu(self.menubar)
        self.menu_app.setObjectName(_fromUtf8("menu_app"))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        self.menu_spot = QtGui.QMenu(self.menubar)
        self.menu_spot.setObjectName(_fromUtf8("menu_spot"))
        SpotGui.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SpotGui)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SpotGui.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(SpotGui)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(SpotGui)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(SpotGui)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.action_save = QtGui.QAction(SpotGui)
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_exit = QtGui.QAction(SpotGui)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_insert_vertex = QtGui.QAction(SpotGui)
        self.action_insert_vertex.setObjectName(_fromUtf8("action_insert_vertex"))
        self.action_insert_edge = QtGui.QAction(SpotGui)
        self.action_insert_edge.setObjectName(_fromUtf8("action_insert_edge"))
        self.action_about = QtGui.QAction(SpotGui)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action_new = QtGui.QAction(SpotGui)
        self.action_new.setObjectName(_fromUtf8("action_new"))
        self.action_node = QtGui.QAction(SpotGui)
        self.action_node.setObjectName(_fromUtf8("action_node"))
        self.action_edge = QtGui.QAction(SpotGui)
        self.action_edge.setObjectName(_fromUtf8("action_edge"))
        self.action_open = QtGui.QAction(SpotGui)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_save_image = QtGui.QAction(SpotGui)
        self.action_save_image.setObjectName(_fromUtf8("action_save_image"))
        self.action_find_by_name = QtGui.QAction(SpotGui)
        self.action_find_by_name.setObjectName(_fromUtf8("action_find_by_name"))
        self.action_add_spot = QtGui.QAction(SpotGui)
        self.action_add_spot.setObjectName(_fromUtf8("action_add_spot"))
        self.action_del_spot = QtGui.QAction(SpotGui)
        self.action_del_spot.setObjectName(_fromUtf8("action_del_spot"))
        self.menu_app.addAction(self.action_exit)
        self.menu_help.addAction(self.action_about)
        self.menu_spot.addAction(self.action_add_spot)
        self.menu_spot.addAction(self.action_del_spot)
        self.menubar.addAction(self.menu_app.menuAction())
        self.menubar.addAction(self.menu_spot.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(SpotGui)
        QtCore.QMetaObject.connectSlotsByName(SpotGui)

    def retranslateUi(self, SpotGui):
        SpotGui.setWindowTitle(_translate("SpotGui", "Spots", None))
        self.color_label.setText(_translate("SpotGui", "Spot Color", None))
        self.red_button.setText(_translate("SpotGui", "Red", None))
        self.green_button.setText(_translate("SpotGui", "Green", None))
        self.blue_button.setText(_translate("SpotGui", "Blue", None))
        self.yellow_button.setText(_translate("SpotGui", "Yellow", None))
        self.cyan_button.setText(_translate("SpotGui", "Cyan", None))
        self.magenta_button.setText(_translate("SpotGui", "Magenta", None))
        self.menu_app.setTitle(_translate("SpotGui", "App", None))
        self.menu_help.setTitle(_translate("SpotGui", "Help", None))
        self.menu_spot.setTitle(_translate("SpotGui", "Spot", None))
        self.actionOpen.setText(_translate("SpotGui", "Open...", None))
        self.actionSave.setText(_translate("SpotGui", "Save", None))
        self.actionSave_As.setText(_translate("SpotGui", "Save As...", None))
        self.action_save.setText(_translate("SpotGui", "Save...", None))
        self.action_exit.setText(_translate("SpotGui", "Exit", None))
        self.action_insert_vertex.setText(_translate("SpotGui", "Vertex...", None))
        self.action_insert_edge.setText(_translate("SpotGui", "Edge...", None))
        self.action_about.setText(_translate("SpotGui", "About", None))
        self.action_new.setText(_translate("SpotGui", "New", None))
        self.action_node.setText(_translate("SpotGui", "Node...", None))
        self.action_edge.setText(_translate("SpotGui", "Edge...", None))
        self.action_open.setText(_translate("SpotGui", "Open...", None))
        self.action_save_image.setText(_translate("SpotGui", "Save Image...", None))
        self.action_find_by_name.setText(_translate("SpotGui", "Find by Name...", None))
        self.action_add_spot.setText(_translate("SpotGui", "Add...", None))
        self.action_del_spot.setText(_translate("SpotGui", "Delete", None))
